---
# Do our basic host setup. Assumes that hosts already have
# correct IP addressing on all interfaces and have connectivity
# to the Ansible orchestrator host via their management
# interfaces.
- hosts: [all-hosts]
  remote_user: "{{ SYSADMIN_NAME }}"
  become: yes
  become_method: sudo
  vars_files:
    - vars/vars.yml
    - vars/passwords.yml
  tasks:
    - name: Copy over User's environment variables
      copy:
        src: "{{ item }}"
        dest: /home/{{ SYSADMIN_NAME }}/
        owner: "{{ SYSADMIN_NAME }}"
        group: "{{ SYSADMIN_NAME }}"
        mode: 0600
        backup: no
      with_items: "{{ SYSADMIN_ENVIRONMENT }}"
    - name: Update .keystone admin token
      replace:
        dest: /home/{{ SYSADMIN_NAME }}/.keystone
        regexp: 'ADMIN_TOKEN'
        replace: "{{ ADMIN_TOKEN }}"
        backup: no
    - name: Update .keystone OS URL
      replace:
        dest: /home/{{ SYSADMIN_NAME }}/.keystone
        regexp: 'CONTROLLER'
        replace: "{{ CONTROLLER }}"
        backup: no
    - name: Update SSH authorized_keys
      authorized_key:
        user: "{{ SYSADMIN_NAME }}"
        key: "{{ SSH_KEY }}"
        manage_dir: yes
    - name: Dist-Upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: Reboot
      command: /sbin/shutdown -r +1
...
