---
# Create the service entity and API endpoints
# http://docs.openstack.org/mitaka/install-guide-ubuntu/keystone-services.html
- hosts: [controllers]
  remote_user: "{{ SYSADMIN_NAME }}"
  become: yes
  become_method: sudo
  vars_files: 
    - vars/vars.yml
    - vars/passwords.yml
  tasks:
    - name: Create the keystone service
      os_keystone_service:
        name: keystone
        service_type: identity
        description: "OpenStack Identity"
        
...
