---
- hosts: [controllers]
  remote_user: "{{ SYSADMIN_NAME }}"
  become: yes
  become_method: sudo
  vars_files:
    - vars/vars.yml
    - vars/passwords.yml
  tasks:
# Run the equivalent of sudo mysql_secure_installation
# Modified from https://github.com/PCextreme/ansible-role-mariadb/blob/master/tasks/mysql_secure_installation.yml
    - name: Set MariaDB root Password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ DB_PASS }}"
        state: present
      with_items: "{{ DB_HOSTS }}"
    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
    - name: Remove anonymous users
      mysql_user:
        name: ''
        state: absent
      changed_when: False
    - name: Disallow root login remotely
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: False
    - name: Remove test database
      mysql_db:
        name: test
        login_user: root
        login_password: "{{ DB_PASS }}"
        state: absent
    - name: Remove access to test database
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False
      ignore_errors: True
    - name: Reload privilege tables
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
...
